

DROP TABLE UUSER;

DROP TABLE TBL_CHAT;
DROP TABLE SOCIALCOMMENT;
DROP TABLE SOCIALMEMBER;
DROP TABLE BOARDCOMMENT;
DROP TABLE CLUBBOARD;
DROP TABLE SOCIAL;
DROP TABLE CLUBMEMBER;
DROP TABLE CLUBBOARD;
DROP TABLE CLUB;
DROP TABLE FAVORITE;
DROP TABLE CATEGORY;
DROP TABLE UUSER;
DROP TABLE FILEDATAS;

SELECT *
FROM UUSER;

CREATE TABLE FILEDATAS(
	FILENAME VARCHAR2(100) PRIMARY KEY --파일이름(변경값)
	,FILEPATHE VARCHAR2(300) --파일위치
	,ORIGINNAME VARCHAR2(100) --파일 원래이름
);\

CREATE TABLE UUSER(										
	ID VARCHAR2(15) PRIMARY KEY --아이디					
	,PASSWORD VARCHAR2(30) NOT NULL --패스워드					
	,NAME VARCHAR2(30) NOT NULL --이름
	,NICKNAME VARCHAR2(30) unique                    
	,BIRTH DATE NOT NULL --생일					
	,PHONE VARCHAR2(20) NOT NULL --핸드폰번호					
	,EMAIL VARCHAR2(100) NOT NULL --이메일					
	,GENDER VARCHAR2(5) NOT NULL --성별			
	,HIDDEN VARCHAR(1) DEFAULT('N')--유령회원여부,
	,DELETED VARCHAR(1) DEFAULT('N') --삭제여부
	,DELETEDATE DATE --데이트 삭제날짜
	,DATELOG DATE --접속한 날짜 설정
	,MANNERPOINT NUMBER
	,PROFILE VARCHAR(100)
,CONSTRAINT chk_gender2 CHECK (GENDER IN ('F','M')),
FOREIGN KEY (PROFILE) REFERENCES FILEDATAS(FILENAME) ON DELETE SET NULL
);

INSERT INTO UUSER(ID,PASSWORD,NAME,NICKNAME,BIRTH,PHONE,EMAIL,GENDER) values('user1','1234','김씨','제임스','1999-01-01','01011111111','email.com','M');
INSERT INTO UUSER(ID,PASSWORD,NAME,NICKNAME,BIRTH,PHONE,EMAIL,GENDER) values('user2','1234','이씨','제이슨','1999-01-01','01011111111','email.com','M');
INSERT INTO UUSER(ID,PASSWORD,NAME,NICKNAME,BIRTH,PHONE,EMAIL,GENDER) values('user3','1234','박씨','김길동','1999-01-01','01011111111','email.com','M');
INSERT INTO UUSER(ID,PASSWORD,NAME,NICKNAME,BIRTH,PHONE,EMAIL,GENDER) values('user4','1234','최씨','에슐리','1999-01-01','01011111111','email.com','M');
INSERT INTO UUSER(ID,PASSWORD,NAME,NICKNAME,BIRTH,PHONE,EMAIL,GENDER) values('user5','1234','김씨','데이비드','1999-01-01','01011111111','email.com','M');
INSERT INTO UUSER(ID,PASSWORD,NAME,NICKNAME,BIRTH,PHONE,EMAIL,GENDER) values('user6','1234','최씨','','1999-01-01','01011111111','email.com','M');



CREATE TABLE CATEGORY(			
	CATEGORY VARCHAR2(50) PRIMARY KEY 
)

INSERT INTO CATEGORY VALUES ('영화');
INSERT INTO CATEGORY VALUES ('등산');
INSERT INTO CATEGORY VALUES ('음악');
INSERT INTO CATEGORY VALUES ('음식');
INSERT INTO CATEGORY VALUES ('전시회');
INSERT INTO CATEGORY VALUES ('게임');
INSERT INTO CATEGORY VALUES ('운동');
INSERT INTO CATEGORY VALUES ('카페');
INSERT INTO CATEGORY VALUES ('자기계발');


CREATE TABLE FAVORITE(	--선호도 리스트
	ID VARCHAR2(15)
	,CATEGORY VARCHAR2(50)
,FOREIGN KEY (ID) REFERENCES UUSER(ID) ON DELETE CASCADE
,FOREIGN KEY (CATEGORY) REFERENCES CATEGORY(CATEGORY) ON DELETE CASCADE
,CONSTRAINT pk_fav PRIMARY KEY(ID,CATEGORY)
);

SELECT * FROM FAVORITE;
INSERT INTO FAVORITE
values('user1','영화');
INSERT INTO FAVORITE
values('user2','영화');
INSERT INTO FAVORITE
values('user1','자기계발');
INSERT INTO FAVORITE
values('user1','전시회');

CREATE SEQUENCE CLUB_SEQ NOCACHE;

안씀----------------------------------------------------------------------------ㄱ
CREATE TABLE CLUB(
	NUM NUMBER PRIMARY KEY		
	,CATEGORY VARCHAR2(50) --카테고리
    ,TITLE VARCHAR2(100) --클럽이름
    ,CONTENT VARCHAR2(300) --클럽 미리보기
    ,CONTENTS VARCHAR2(900) --클럽내용
    ,CLUBIMAGE VARCHAR2(100)
,FOREIGN KEY (CATEGORY) REFERENCES CATEGORY(CATEGORY) ON DELETE CASCADE
,FOREIGN KEY (CLUBIMAGE) REFERENCES FILEDATAS(FILENAME) ON DELETE SET NULL 
);
);
CREATE SEQUENCE CLUBMEMBER_SEQ NOCACHE;
CREATE TABLE CLUBMEMBER(
	NUM NUMBER --클럽 고유 넘버
	,ID VARCHAR2(15) --유저 아이디
	,NICKNAME VARCHAR2(20) --유저 아이디
	,AUTH VARCHAR2(2) DEFAULT('U') --등급
,CONSTRAINT AUTH CHECK (AUTH IN ('M','U','S'))
,CONSTRAINT CLUBMEMBER_pk PRIMARY KEY(NUM,ID)
,FOREIGN KEY (ID) REFERENCES UUSER(ID) ON DELETE CASCADE
,FOREIGN KEY (NICKNAME) REFERENCES UUSER(NICKNAME) ON DELETE CASCADE
,FOREIGN KEY (NUM) REFERENCES CLUB(NUM) ON DELETE CASCADE
);
CREATE SEQUENCE CLUBBOARD_SEQ NOCACHE;
CREATE TABLE CLUBBOARD(
	NUM NUMBER --클럽 고유 넘버
	,BOARDNUM NUMBER PRIMARY KEY --게시글 번호
	,TITLE VARCHAR2(900) --게시글 이름
	,CONTENTS VARCHAR2(900) --게시글 내용
	,FILENAME VARCHAR2(100) --게시판 첨부팡일
	,WRITER VARCHAR2(100) --글쓴이
	,NICKNAME VARCHAR2(20)
	,WRITEDATE DATE DEFAULT(SYSDATE) --글쓴날
	,REWRITEDATE DATE --글수정날
	,VIEWED NUMBER --조회수
,FOREIGN KEY (WRITER) REFERENCES UUSER(ID) ON DELETE SET NULL
,FOREIGN KEY (NICKNAME) REFERENCES UUSER(NICKNAME) ON DELETE SET NULL
,FOREIGN KEY (NUM) REFERENCES CLUB(NUM) ON DELETE CASCADE
,FOREIGN KEY (FILENAME) REFERENCES FILEDATAS(FILENAME) ON DELETE SET NULL
);
CREATE SEQUENCE BOARDCOMMENT_SEQ NOCACHE;
CREATE TABLE BOARDCOMMENT(
	COMMENTNUM NUMBER PRIMARY KEY--덧글 번호
	,BOARDNUM NUMBER--게시글 번호
	,WRITER VARCHAR(100) --글쓴이
	,NICKNAME VARCHAR2(20)
	,WRITEDATE DATE DEFAULT(SYSDATE) --글쓴날
	,REWRITEDATE DATE --글수정날
	,FILENAME VARCHAR2(100) --게시판 첨부팡일
,FOREIGN KEY (WRITER) REFERENCES UUSER(ID) ON DELETE SET NULL
,FOREIGN KEY (NICKNAME) REFERENCES UUSER(NICKNAME) ON DELETE SET NULL
,FOREIGN KEY (BOARDNUM) REFERENCES CLUBBOARD(BOARDNUM) ON DELETE CASCADE
,FOREIGN KEY (FILENAME) REFERENCES FILEDATAS(FILENAME) ON DELETE SET NULL
);
SELECT * FROM SOCIAL s
FULL JOIN SOCIALMEMBER m ON s.SOCIALNUM=m.SOCIALNUM;
---------------------------------------------------------------------------ㄴ

CREATE SEQUENCE SOCIAL_SEQ NOCACHE;
CREATE TABLE SOCIAL(
	SOCIALNUM NUMBER PRIMARY KEY		
	,CATEGORY VARCHAR2(50) --카테고리
    ,TITLE VARCHAR2(100) --클럽이름
    ,CONTENT VARCHAR2(300) --클럽 미리보기
    ,CONTENTS VARCHAR2(900) --클럽내용
    ,MAXIMUM NUMBER
    ,SOCIALIMAGE VARCHAR2(100)
    ,SOCIALCLUB VARCHAR2(3)
,FOREIGN KEY (CATEGORY) REFERENCES CATEGORY(CATEGORY) ON DELETE CASCADE
,FOREIGN KEY (SOCIALIMAGE) REFERENCES FILEDATAS(FILENAME) ON DELETE SET NULL 
);

CREATE TABLE SOCIALMEMBER(
	SOCIALNUM NUMBER --클럽 고유 넘버
	,ID VARCHAR2(15) --유저 아이디
	,NICKNAME VARCHAR2(15) --유저 아이디
	,AUTH VARCHAR2(2) DEFAULT('U') --등급
,CONSTRAINT AUTH2 CHECK (AUTH IN ('M','U','S'))
,CONSTRAINT SOCIAL2_pk PRIMARY KEY(SOCIALNUM,ID)
,FOREIGN KEY (ID) REFERENCES UUSER(ID) ON DELETE CASCADE
,FOREIGN KEY (NICKNAME) REFERENCES UUSER(NICKNAME) ON DELETE CASCADE
,FOREIGN KEY (SOCIALNUM) REFERENCES SOCIAL(SOCIALNUM) ON DELETE CASCADE
);

CREATE SEQUENCE CLUBBOARD_SEQ NOCACHE;
CREATE TABLE CLUBBOARD(
	NUM NUMBER --클럽 고유 넘버
	,BOARDNUM NUMBER PRIMARY KEY --게시글 번호
	,TITLE VARCHAR2(900) --게시글 이름
	,CONTENTS VARCHAR2(900) --게시글 내용
	,FILENAME VARCHAR2(100) --게시판 첨부팡일
	,WRITER VARCHAR2(100) --글쓴이
	,NICKNAME VARCHAR2(20)
	,WRITEDATE DATE DEFAULT(SYSDATE) --글쓴날
	,REWRITEDATE DATE --글수정날
	,VIEWED NUMBER --조회수
,FOREIGN KEY (WRITER) REFERENCES UUSER(ID) ON DELETE SET NULL
,FOREIGN KEY (NICKNAME) REFERENCES UUSER(NICKNAME) ON DELETE SET NULL
,FOREIGN KEY (NUM) REFERENCES SOCIAL(SOCIALNUM) ON DELETE CASCADE
,FOREIGN KEY (FILENAME) REFERENCES FILEDATAS(FILENAME) ON DELETE SET NULL
);

CREATE SEQUENCE COMMENTNUM_SEQ NOCACHE;
CREATE TABLE SOCIALCOMMENT(
	COMMENTNUM NUMBER PRIMARY KEY--덧글 번호
	,SOCIALNUM NUMBER--후기 번호
	,BOARDNUM NUMBER --
	,WRITER VARCHAR(100) --글쓴이
	,WRITEDATE DATE DEFAULT(SYSDATE) --글쓴날
	,REWRITEDATE DATE --글수정날
	,FILENAME VARCHAR2(100) --게시판 첨부팡일
,FOREIGN KEY (WRITER) REFERENCES UUSER(ID) ON DELETE CASCADE
,FOREIGN KEY (SOCIALNUM) REFERENCES SOCIAL(SOCIALNUM) ON DELETE CASCADE
,FOREIGN KEY (BOARDNUM) REFERENCES CLUBBOARD(BOARDNUM) ON DELETE CASCADE
,FOREIGN KEY (FILENAME) REFERENCES FILEDATAS(FILENAME) ON DELETE SET NULL
);



CREATE SEQUENCE TBL_CHAT_SEQ NOCACHE;
CREATE TABLE TBL_CHAT(
   id NUMBER PRIMARY KEY, --채팅넘버
   ITEM_ID VARCHAR2(40), --채팅방이름
    SENDER VARCHAR2(40) NOT NULL, --보낸
    MESSAGE VARCHAR2(1000) NOT NULL,--내용
   RECEIVER VARCHAR2(40),--받는
    WRITEDAY DATE DEFAULT(SYSDATE)--전송일
,FOREIGN KEY (SENDER) REFERENCES UUSER(ID) ON DELETE CASCADE
,FOREIGN KEY (RECEIVER) REFERENCES UUSER(ID) ON DELETE CASCADE
);




COMMIT;

